// Generated by https://quicktype.io

export interface GroupBody {
  destination: string;
  departureDate: string;
  returnDate: string;
  itinerary: string;
  budget: number;
  interests: string[];
  minimumNumberOfMembers: number;
}
