// Generated by https://quicktype.io

export interface ReadyGroup {
  content: ReadyContent[];
  pageable: Pageable;
  totalPages: number;
  totalElements: number;
  last: boolean;
  size: number;
  number: number;
  sort: Sort;
  numberOfElements: number;
  first: boolean;
  empty: boolean;
}

export interface ReadyContent {
  id: number;
  destination: string;
  departureDate: string;
  returnDate: string;
  itinerary: string;
  budget: number;
  owner: Owner;
  interests: string[];
  minimumNumberOfMembers: number;
  travelers: Owner[];
  totalTravelers: number;
}

export interface Owner {
  username: string;
  name: string;
  profilePicture: null;
  id: number;
}

export interface Pageable {
  pageNumber: number;
  pageSize: number;
  sort: Sort;
  offset: number;
  paged: boolean;
  unpaged: boolean;
}

export interface Sort {
  empty: boolean;
  sorted: boolean;
  unsorted: boolean;
}
