// Generated by https://quicktype.io

export interface RegisterReq {
  name: string;
  email: string;
  phoneNumber: string;
  address: string;
  gender: string;
  country: Country;
  interest: Interest[];
  username: string;
  password: string;
  role: string;
}

export interface Country {
  name: string;
}
export interface Interest {
  name: string;
}
